### ISSUE TITLE
Request - Select Super Source Background

### ISSUE THREAD

**Issue by Rowy5446** [bitfocus/companion-module-bmd-atem#135]
ATEM Mini Extreme ISO
Can select super source box source but can't find a way of changing the background.
Super Source - Art - Fill Source on the ATEM Software Control

**Comment by marteloudini** [comment]
me too, this is a feature that could be very nice

**Comment by thomascantrellsea** [comment]
Add my vote here as well, can always workaround with a macro - but I definitely went looking for this functionality just now.

**Comment by davidjoshuaford** [comment]
Adding my vote for this as well!

**Comment by Julusian** [comment]
This is now implemented

**Comment by davidjoshuaford** [comment]
Amazing, thank you!

**Comment by davidjoshuaford** [comment]
Hi @Julusian, one more thing in implementing the Art - can there be an action so you can Toggle between Foreground and Background placement? 

Similarly, when placing Art, the options currently force placement in either Foreground or Background. Could there be a third option that will not alter foreground/background status when selecting an art input? 

Reason being - to build a Companion page for all the possible art inputs, it doubles the number of buttons necessary to choose an input (since it will force either background or foreground).

**Comment by davidjoshuaford** [comment]
Also heads up - the Feedback for "atem: SuperSorce: Art fill source" does not appear to be updating correctly. 

(also- spelling on "SuperSorce" :)

Cheers, David

**Comment by Julusian** [comment]
Good spot, should be fixed now.
Its been a while since I added more feedbacks, and I missed a step...

**Comment by andreaskielwein** [comment]
Hey, can you help me?
To change fore- and background is not an issue any more in SSRC.
But I can’t find a solution so read the Status and the Title of the Background Art Layer in SSRC with $
Thanks
