### ISSUE TITLE
Atem Constellation HD 2ME

### ISSUE THREAD

**Issue by pjjgrapher** [bitfocus/companion-module-bmd-atem#181]
Hi,

I've received the new brand Constellation HD 2ME. I've already the Constellation 8K, and other Atem Mini (Extrem, and pro).
I'm trying to connect with companion for an event in few days, I'm unable to connect it proprely.

I've seen that companion support the version 8.6, the new constellation needs the 8.7.

Do you plan to update the support? do you have any solution to 'solve'? 

Thanks for the job,
<img width="1728" alt="Screenshot 2022-05-12 at 10 30 18" src="https://user-images.githubusercontent.com/15836474/168031073-5c68bddb-055c-430c-9e94-186b2324feac.png">

**Comment by Julusian** [comment]
Either ignore the warning or use a recent beta. The problem is that the 2.2.0 release you are using pre-dates that atem model by a couple of months, so it is unaware of the model. But it can make a pretty good guess at what it supports, so it should be fine. The recent betas do know about that model (based on some guesswork)

Would you mind running https://builds.julusian.dev/atem/ for me? It will generate some test data from your atem (it only reads, doesnt change anything) that will help me verify things work with it
