### ISSUE TITLE
AUX feedback from variable

### ISSUE THREAD

**Issue by petripeura** [bitfocus/companion-module-bmd-atem#226]
Hi and thanks for "Aux/Output: Set source from variables"
How about the same functionality for AUX feedback?

Example: I have a custom variable "SelectedAux" and now I need to set the style with that.
Or am I missing something how to make it?

Petri

**Comment by davidjoshuaford** [comment]
I think you are correct that this needs further development. For example, on my 2ME, while I could add twelve feedbacks to an Input1 button, for example, to highlight yellow if an AUX 1-12 is active, that wouldn't identify for me me which AUX variable is currently selected.

I've mentioned it previously here https://github.com/bitfocus/companion-module-bmd-atem/issues/157

**Comment by Julusian** [comment]
This is blocked on Companion not properly supporting variables in feedbacks.
I can write the feedback and it will work when the aux input changes, but it won't update when the referenced variables change.

Is it possible to achieve the same by using the `internal: Compare variable` feedbacks? They do properly respond to changes in their variables.

**Comment by davidjoshuaford** [comment]
Unless I'm missing something, I am finding that I can only partly implement correct feedback changes for variables. 

Here's an example of of a single page I'm building to control ME1, ME2 & AUX1-12 for my 2ME Constellation HD on page 15: 

<img width="687" alt="Screenshot 2022-12-15 at 11 31 48 AM" src="https://user-images.githubusercontent.com/76959770/207918502-04253cb7-d3e4-4afc-b03e-bb8fa665df36.png">

<img width="688" alt="Screenshot 2022-12-15 at 11 32 02 AM" src="https://user-images.githubusercontent.com/76959770/207918540-f548ff17-1e72-4153-b090-9f3d2c784fdd.png">

15.2 toggles selection of: ME1 PVW / ME1 PGM,
15.3 toggles selection of: ME2 PVW / ME2 PGM,
15.4 through 15.16 selects: AUX1 – AUX12 respectively, 

then, buttons 17-32 will be the Input buttons that change state according to the variables selected on the ME1/2/AUX in the first two rows.

Here's an example of using the "internal: check variable value" feedback to show on all my Input buttons that my custom variable "custom_aux" has been selected. The first red box highlighted here shows a value greater than 0, because my aux value is 1, to correspond with AUX 1, and therefore all Input buttons have a dark yellow background color to indicate I'm selecting AUX1 (and not the dark red or dark green of the PGM/PVW of the MEs): 

<img width="1753" alt="Screenshot 2022-12-15 at 11 35 18 AM" src="https://user-images.githubusercontent.com/76959770/207920248-950eced6-82e8-42c0-b2f8-c8c6d4bf57de.png">

The problem is in the second red box (where I'm using bright yellow to indicate the input is active on the AUX) – I cannot isolate ACTIVE feedback to show ONLY the AUX 1's selection. It would need to accept my custom variable "custom_aux" to isolate the AUX channel I have selected. 

The feedback "Internal: Check variable value" and "internal: Compare variable to variable" do not work for this because it is only comparing one value to another... in this instance, my custom_aux value = 1, but that does not show me, for example, if Input 17 was routed to AUX 1, for example.

I could add twelve "atem: Aux/Output: Source" feedbacks to each Input button, but again, that would show me ALL auxiliaries, where as I need it isolated, such that when AUX1 is selected, I see ONLY which Input is selected on AUX 1.

The solve here as far a I can see is for the feedback "atem: Aux/Output: Source" to accept a custom variable in the "AUX" field. (likewise, the same would go for the ME1 and ME2 PGM and PVWs...)

Let me know if I missed anything here!

Cheers, 
David

**Comment by davidjoshuaford** [comment]
Any thoughts on if adding custom variable support to the AUX field of the "atem: Aux/Output: Source" Action would solve this? 

Likewise for the Program and Preview variables. Cheers!

**Comment by Julusian** [comment]
It sounds like it might, and now that companion can support variables in feedback it is possible in this module too!

**Comment by davidjoshuaford** [comment]
The problem I'm encountering is if I set up feedback for AUX1, and then also for AUX2 and so on, there's no way to distinguish between if I'm currently switching AUX1 or AUX2. Both feedbacks will show at the same time, if they're active. Any thoughts on how to resolve this?

**Comment by Julusian** [comment]
![image](https://user-images.githubusercontent.com/1327476/216121421-36b52249-b3f1-4749-a7d2-7cb8eefcc940.png)

I made these last night, doesnt this do enough?

**Comment by davidjoshuaford** [comment]
It needs one more conditional value. 

Illustrated here, I have CamA assigned to AUX1, and CamB assigned to AUX2, but you can see that when AUX2 is selected, the feedback also shows CamA as active. This is because it's showing CamA=AUX1 as true, but to the user who thinks they are switching on the AUX2 bus, this is confusing feedback.  

Need a scenario where by when the "internal:custom_aux" variable is set to "2" (or any other AUX number), that the AUX1 feedback on the CamA button is _not true_ ...ie doesn't show up as highlighted.

Such that when AUX2's custom variable is selected, the input buttons only show feedback as it relates to AUX2.

I think the logic might be:

```
IF

$(internal:custom_aux)
= 
AUX: 2

AND

$(atem:aux2_input_id)
=
Input ID: 2
```

THEN show the various feedback options.

However, for a 2ME constellation with 12 outputs and 2 PGM and 2 PVW, this would still require building out 16 feedback states for approximately 32 input buttons... 512 different feedback states to manage... Perhaps you have an idea of how to simplify that? 

![Screenshot 2023-02-01 at 1 04 02 PM](https://user-images.githubusercontent.com/76959770/216129649-7aabf28f-c895-43dd-9b68-b8be00970c6c.png)

**Comment by davidjoshuaford** [comment]
I think it does, thanks! I'll double check on my 2ME in the studio next week as I only have an ATEM Pro at home with 1 aux, but it seems to reference the selected custom AUX. 

Would it be possible to push these bmd-atem module updates into a Companion 2.4.3 release? I have a number of essential modules needed to run a show (listed below for reference) that aren't supported/stable in v3.0 yet, but would like to start reconfiguring the ATEM in the 2.4.x build in the mean time.  

- H2R
- Canon PTZ
- OBS
- Timestamp
- TP Link Kasa Smart Plug
- WebPresenter

**Comment by Julusian** [comment]
> Would it be possible to push these bmd-atem module updates into a Companion 2.4.3 release?

No, it isnt possible to use variables in feedbacks in 2.4. (Well, it might be by abusing things, but I really dont want to have to get into the headspace of figuring out how 2.4 works again)

**Comment by davidjoshuaford** [comment]
Fair enough, I'll wait for those other modules to make the v3 upgrade. Thanks Julian!

**Comment by petripeura** [comment]
Thank You! This feature works very well!
