### ISSUE TITLE
SuperSource: Set box source from variables

### ISSUE THREAD

**Issue by roms75** [bitfocus/companion-module-bmd-atem#227]
Hi Guys,

Thx for all the great work and evolutions we developped here. 
I just have one request about the last update. Is it possible to do the same action as "Set Program input from variables" but for the box sources?

Thx guys

**Comment by gletiecq** [comment]
another +1 here.

When building companion pages to select box input assignments in a supersource, you need to have four boxes per supersource since the boxIndex parameter is defined as a dropdown in inputs.ts\ATEMSuperSourceBoxPicker and used in actions.ts.  If instead boxIndex and superSourceIndex were set as text input boxes, internal variables could be used in companion.  This would reduce the number of companion pages needed to accomplish this to a single page.  Input value checking would definitely be advisable to ensure the values are within the range of the device's capabilities, which is currently avoided since the input interface is a dropdown box.

In ActionId.SuperSourceBoxSourceVaraibles (action.ts) this is provided as a textinput so it seems the functionality already exists to support this by substituting the definition in input.ts and adding some simple input checking, so I'm hopeful the change would be quick to make.  I'm not much familiar with node.js so my evaluation could easily be faulty, otherwise I'd provide a code proposal.

**Comment by Julusian** [comment]
The `Set box source from variables` action already does set from variables.
We don't need to bother with validating the number, as the atem will ignore a command with invalid values.

**Comment by davidjoshuaford** [comment]
Is there a value I can place in the "Box #" to change the Art Fill source?

![Screenshot 2023-06-16 at 4 25 20 PM](https://github.com/bitfocus/companion-module-bmd-atem/assets/76959770/e3e3a4e7-db2f-431a-ad99-d7324650ca15)
