### ISSUE TITLE
ATEM not connecting  after reboot on PI

### ISSUE THREAD

**Issue by zhoma0902** [bitfocus/companion-module-bmd-atem#333]
I just installed on PI 3b all my things work. When I reboot the Pi it will not reconnect to the ATEM. It keeps on crashing for the ATEM connection only.![Image](https://github.com/user-attachments/assets/3ed170ce-83b9-45b7-a681-b878adbe3e8e)

**Comment by Julusian** [comment]
What does the log say?

**Comment by zhoma0902** [comment]
Here is a screen shot of the logs. [Image](https://github.com/user-attachments/assets/f71035e3-09ef-4ff9-b0dc-f197eb866766)

**Comment by zhoma0902** [comment]
here is the log for the ATEM connection from the three dots on the ATEM connection. ![Image](https://github.com/user-attachments/assets/a2225d6e-6eba-4244-8f9c-2824acfcb991)

**Comment by zhoma0902** [comment]
Here is an exported log. [module-log-11_3_2024-9_42_56 AM.csv](https://github.com/user-attachments/files/17611248/module-log-11_3_2024-9_42_56.AM.csv)

**Comment by Julusian** [comment]
This looks like the module is taking too long to launch, so companion is assuming it has gotten stuck is killing it and then trying again.

I don't think there is anything we can do to mitigate this.

It is worth noting that the pi3b is not a supported platform, mostly because of reliability issues with the usb/networking, but also because 1GB of memory is not really enough for companion.
