### ISSUE TITLE
Feedback "Audio Routing from variables" not working for channels 9-10, 11-12, 13-14, 15-16

### ISSUE THREAD

**Issue by BenesRadovan** [bitfocus/companion-module-bmd-atem#343]
Hello, I think I might discovered a possible bug. When I create "Fairlight Audio: Audio Routing from variables" and try it with audio channels up to 7_8 (2012-1_2, 2012-3_4, 2012-5_6, 2012-7_8), it works as expected. But when I use it with channels 9_10, 11_12, 13_14, 15_16, I'm not able to get any feedback even I am 100% sure the actual routing is done. For example destination 2012-15_16 with source 2101-1_2 gives me no feedback, even Im hearing production talkback on AUX 12 channels 15-16. "Fairlight Audio: Audio Routing" works as expected. Tried with Constellation 2M/E HD and Constellation 4M/E 4K.

**Comment by YveIce** [comment]
in [companion-module-bmd-atem/src/util.ts](https://github.com/bitfocus/companion-module-bmd-atem/blob/main/src/util.ts):125
```diff
- const ROUTING_STRING_REGEX = /(\d+)-([\d]+_[\d+])/i
+ const ROUTING_STRING_REGEX = /(\d+)-([\d]+_[\d]+)/i
```
**[\d+]** truncates the last digits, so that “2001-9_10” is interpreted as “2001-9_1”, so that the following code cannot be resolved to the correct pairValueOption. It should be **[\d]+**.

**Comment by Julusian** [comment]
Thanks for the fix, this will be in the betas shortly
